function MetaAnalysis1 = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  METAANALYSIS1 = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  METAANALYSIS1 = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  MetaAnalysis1 = importfile1("/Users/elysiasmyers/Documents/MATLAB/Data/Meta-Analysis.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Aug-2020 11:15:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "YieldStressPa", "ExtensionalStraintoBreak", "TypePphysicalCcovalentSSinglemolecule", "Var8", "Var9", "Var10"];
opts.SelectedVariableNames = ["YieldStressPa", "ExtensionalStraintoBreak", "TypePphysicalCcovalentSSinglemolecule"];
opts.VariableTypes = ["string", "string", "string", "string", "double", "double", "categorical", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var8", "Var9", "Var10"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "TypePphysicalCcovalentSSinglemolecule", "Var8", "Var9", "Var10"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "YieldStressPa", "TrimNonNumeric", true);
opts = setvaropts(opts, "YieldStressPa", "ThousandsSeparator", ",");

% Import the data
MetaAnalysis1 = readtable(filename, opts);

end